import type { HomePosterConfig } from '@/lib/types';
export const defaultHomePosterConfig: HomePosterConfig = {
  heroSlides: [
    {
      id: 'default-hero-1',
      title: 'Experience UniNest',
      subtitle: "Connect, learn, and shop smarter with India's favorite student hub",
      imageUrl: 'https://placehold.co/1600x500/orange/white?text=Welcome+to+UniNest',
      ctaLabel: 'Join Now',
      ctaHref: '/signup',
      secondaryCtaLabel: 'Explore',
      secondaryCtaHref: '/feed',
      tag: 'Featured',
    },
  ],
  quickAccessCards: [
    {
      id: 'default-quick-1',
      title: 'Marketplace deals',
      description: 'Fresh finds under ₹199',
      href: '/marketplace',
      imageUrl: 'https://placehold.co/400x220/ffe2cc/31220c?text=Marketplace',
      icon: 'package',
    },
    {
      id: 'default-quick-2',
      title: 'Peer study rooms',
      description: 'Start a collaborative session',
      href: '/workspace',
      imageUrl: 'https://placehold.co/400x220/d6e6ff/0a1f44?text=Study+Hub',
      icon: 'users',
    },
    {
      id: 'default-quick-3',
      title: 'Download fresh notes',
      description: 'Expert summaries & solved papers',
      href: '/notes',
      imageUrl: 'https://placehold.co/400x220/e4f7d7/143a04?text=Notes',
      icon: 'book-open',
    },
    {
      id: 'default-quick-4',
      title: 'Join the social buzz',
      description: 'Trending conversations from campuses',
      href: '/feed',
      imageUrl: 'https://placehold.co/400x220/f4e2ff/240835?text=Social+Feed',
      icon: 'arrow-right',
    },
  ],
  curatedCollections: [
    {
      id: 'default-collection-1',
      title: 'Last-minute competition prep',
      description: 'Register for top hackathons and contests closing soon.',
      href: '/workspace/competitions',
      imageUrl: 'https://placehold.co/500x300/fff0f0/661111?text=Competitions',
    },
    {
      id: 'default-collection-2',
      title: 'Internships ready to apply',
      description: 'Handpicked roles from verified partners for UniNest students.',
      href: '/workspace/internships',
      imageUrl: 'https://placehold.co/500x300/ebfff4/0b3d24?text=Internships',
    },
    {
      id: 'default-collection-3',
      title: 'Upgrade your hostel life',
      description: 'Comfort essentials and gadgets from verified vendors.',
      href: '/marketplace?category=hostel',
      imageUrl: 'https://placehold.co/500x300/eff3ff/172152?text=Hostel+Essentials',
    },
  ],
  mobileDeals: [
    {
      title: 'Hostel Essentials',
      subtitle: 'Comfort upgrades under ₹999',
      href: '/marketplace?category=Hostels',
      gradient: 'from-[#7928CA] via-[#FF0080] to-[#FF4D4D]',
      icon: 'gift',
    },
    {
      title: 'Campus Notes',
      subtitle: 'Verified notes & guides',
      href: '/notes',
      gradient: 'from-[#1FA2FF] via-[#12D8FA] to-[#A6FFCB]',
      icon: 'package',
    },
    {
      title: 'Internship Leads',
      subtitle: 'Top roles closing soon',
      href: '/workspace/internships',
      gradient: 'from-[#F7971E] via-[#FFD200] to-[#FF512F]',
      icon: 'sparkles',
    },
    {
      title: 'Learning Booster',
      subtitle: 'Skill programs for students',
      href: '/workspace/competitions',
      gradient: 'from-[#8360C3] via-[#2EBF91] to-[#36D1DC]',
      icon: 'graduation-cap',
    },
  ],
  stats: [
    {
      value: 12000,
      label: 'Students empowered',
      icon: 'users',
      isPlus: true,
    },
    {
      value: 260,
      label: 'Verified campus partners',
      icon: 'building',
      isPlus: true,
    },
    {
      value: 80,
      label: 'Libraries & study hubs',
      icon: 'library',
      isPlus: true,
    },
  ],
  testimonials: [
    {
      name: 'Ananya Verma',
      quote: 'UniNest helped me discover internships I never knew existed. The community keeps me motivated.',
      school: 'Delhi University',
      avatar: 'https://i.pravatar.cc/160?img=48',
    },
    {
      name: 'Rahul Mehta',
      quote: 'From study material to hostel essentials, everything I need is now in one place.',
      school: 'IIT Bombay',
      avatar: 'https://i.pravatar.cc/160?img=12',
    },
    {
      name: 'Sara Khan',
      quote: 'The competitions board keeps our entire club up to date with the best opportunities.',
      school: 'BITS Pilani',
      avatar: 'https://i.pravatar.cc/160?img=30',
    },
  ],
  timeline: [
    {
      year: '2024',
      title: 'Launch on campus',
      description: 'Started with a small community of passionate students.',
      icon: 'sparkles',
    },
    {
      year: '2024 Q3',
      title: 'Marketplace expansion',
      description: 'Onboarded 100+ verified vendors and service partners.',
      icon: 'store',
    },
    {
      year: '2025',
      title: 'Learning ecosystem',
      description: 'Brought internships, competitions, and study resources under one roof.',
      icon: 'rocket',
    },
    {
      year: 'Next',
      title: 'Global student network',
      description: 'Connecting campuses worldwide for shared growth.',
      icon: 'globe',
    },
  ],
};
