import type { HomePosterConfig } from '@/lib/types';

export const defaultHomePosterConfig: HomePosterConfig = {
  heroSlides: [
    {
      id: 'social-energy',
      title: 'Plug into the UniNest Social Hub',
      subtitle: 'Share moments, follow friends, and stay in sync with every campus pulse.',
      imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1600&q=80',
      ctaLabel: 'Explore Social',
      ctaHref: '/social',
      secondaryCtaLabel: 'Jump to Feed',
      secondaryCtaHref: '/feed',
      tag: 'Student Life',
    },
    {
      id: 'market-discoveries',
      title: 'Discover Campus Essentials Instantly',
      subtitle: 'Shop curated supplies, hostels, and services tailored for student life.',
      imageUrl: 'https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?auto=format&fit=crop&w=1600&q=80',
      ctaLabel: 'Visit Marketplace',
      ctaHref: '/marketplace',
      secondaryCtaLabel: 'Book a Hostel',
      secondaryCtaHref: '/booking',
      tag: 'Marketplace',
    },
    {
      id: 'workspace-upskill',
      title: 'Grow Faster with UniNest Workspace',
      subtitle: 'Find internships, competitions, and learning tracks designed for ambitious students.',
      imageUrl: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?auto=format&fit=crop&w=1600&q=80',
      ctaLabel: 'Browse Workspace',
      ctaHref: '/workspace',
      secondaryCtaLabel: 'View Competitions',
      secondaryCtaHref: '/workspace/competitions',
      tag: 'Opportunities',
    },
  ],
  quickAccessCards: [
    {
      id: 'quick-social',
      title: 'Social Hub',
      description: 'Catch up with trending posts from your community.',
      href: '/social',
      imageUrl: 'https://images.unsplash.com/photo-1521986329282-0436c1e63c86?auto=format&fit=crop&w=800&q=80',
      icon: 'users',
    },
    {
      id: 'quick-feed',
      title: 'Campus Feed',
      description: 'Share updates, like posts, and join conversations.',
      href: '/feed',
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      icon: 'sparkles',
    },
    {
      id: 'quick-market',
      title: 'Marketplace',
      description: 'Shop verified listings from hostel beds to stationery.',
      href: '/marketplace',
      imageUrl: 'https://images.unsplash.com/photo-1515169067865-5387ec356754?auto=format&fit=crop&w=800&q=80',
      icon: 'store',
    },
    {
      id: 'quick-workspace',
      title: 'Workspace',
      description: 'Level up with internships and competitions hand-picked for you.',
      href: '/workspace',
      imageUrl: 'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=800&q=80',
      icon: 'rocket',
    },
  ],
  curatedCollections: [
    {
      id: 'collection-social',
      title: 'Connect & Collaborate',
      description: 'Jump into curated spaces built for meaningful interactions.',
      href: '/social',
      imageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=80',
    },
    {
      id: 'collection-market',
      title: 'Campus Marketplace',
      description: 'Browse community-approved vendors and student-led services.',
      href: '/marketplace',
      imageUrl: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1400&q=80',
    },
    {
      id: 'collection-work',
      title: 'Career Boost Corner',
      description: 'Showcase your skills, join competitions, and get noticed.',
      href: '/workspace',
      imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1400&q=80',
    },
  ],
  mobileDeals: [
    {
      title: 'Daily Social Spotlight',
      subtitle: 'See what batchmates are sharing right now.',
      href: '/feed',
      gradient: 'from-blue-500 via-purple-500 to-pink-500',
      icon: 'sparkles',
    },
    {
      title: 'UniNest Deals',
      subtitle: 'Unlock exclusive offers and cashback on student favorites.',
      href: '/marketplace',
      gradient: 'from-amber-500 via-orange-500 to-rose-500',
      icon: 'gift',
    },
  ],
  stats: [
    {
      value: 12000,
      label: 'Students onboarded',
      icon: 'users',
      isPlus: true,
    },
    {
      value: 480,
      label: 'Vendors listed',
      icon: 'store',
      isPlus: true,
    },
    {
      value: 3200,
      label: 'Daily interactions',
      icon: 'message-square',
      isPlus: true,
    },
  ],
  testimonials: [
    {
      name: 'Ayesha Khan',
      quote: 'UniNest keeps me updated on everything—from hostel events to study groups—without the noise.',
      school: 'SRM Institute of Science and Technology',
      avatar: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=256&q=80',
    },
    {
      name: 'Rohan Sharma',
      quote: 'I discovered my internship and made new friends through the social hub in less than a week.',
      school: 'IIT Bombay',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    },
    {
      name: 'Nandini Rao',
      quote: 'It feels like my entire campus life lives in one app—marketplace, social feed, and more.',
      school: 'Christ University',
      avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=256&q=80',
    },
  ],
  timeline: [
    {
      year: '2022',
      title: 'UniNest was born',
      description: 'Built to empower students with a digital-first campus experience.',
      icon: 'sparkles',
    },
    {
      year: '2023',
      title: 'Marketplace launched',
      description: 'Local vendors and student entrepreneurs found their new home.',
      icon: 'store',
    },
    {
      year: '2024',
      title: 'Social hub expansion',
      description: 'Introduced community feeds, direct messaging, and intelligent matching.',
      icon: 'users',
    },
    {
      year: '2025',
      title: 'Workspace 2.0',
      description: 'AI-powered discovery for internships, competitions, and mentors.',
      icon: 'rocket',
    },
  ],
};
