name: Create Production Builds

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production

  build_ios:
    type: build
    params:
      platform: ios
      profile: production
