-- Migration: Add Marketplace Features (Images, Variants, Reviews)
-- Run this in your Supabase SQL Editor

-- 1. Product Images (for multiple images per product)
CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    image_url TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Product Variants (for Size, Color, etc.)
CREATE TABLE IF NOT EXISTS product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL, -- e.g. "Size", "Color"
    value TEXT NOT NULL, -- e.g. "Medium", "Red"
    price_modifier NUMERIC DEFAULT 0, -- e.g. +100 or -50
    stock_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Product Reviews (Ratings and Comments)
CREATE TABLE IF NOT EXISTS product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(product_id, user_id) -- One review per product per user
);

-- Enable RLS
ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_reviews ENABLE ROW LEVEL SECURITY;

-- Policies for Images
CREATE POLICY "Public images are viewable by everyone" 
ON product_images FOR SELECT USING (true);

CREATE POLICY "Sellers can manage images" 
ON product_images FOR ALL 
USING (auth.uid() = (SELECT seller_id FROM products WHERE id = product_images.product_id));

-- Policies for Variants
CREATE POLICY "Public variants are viewable by everyone" 
ON product_variants FOR SELECT USING (true);

CREATE POLICY "Sellers can manage variants" 
ON product_variants FOR ALL 
USING (auth.uid() = (SELECT seller_id FROM products WHERE id = product_variants.product_id));

-- Policies for Reviews
CREATE POLICY "Reviews are viewable by everyone" 
ON product_reviews FOR SELECT USING (true);

CREATE POLICY "Authenticated users can create reviews" 
ON product_reviews FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own reviews" 
ON product_reviews FOR DELETE 
USING (auth.uid() = user_id);
