-- =============================================================================
-- UNINEST MASTER SCHEMA RESTORATION SCRIPT
-- =============================================================================
-- This script contains all table definitions, functions, RLS policies, 
-- and indexes required to restore the UniNest backend from scratch.
-- 
-- WARNING: Run this on a FRESH Supabase project. 
-- Avoid running on existing data unless you use "IF NOT EXISTS".
-- =============================================================================

-- 0. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";
CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

-- 0.1 STORAGE BUCKETS
-- Note: Recreating buckets via SQL. You may need to adjust RLS for these separately.
INSERT INTO storage.buckets (id, name, public)
VALUES 
  ('UniNest', 'UniNest', true),
  ('avatars', 'avatars', true),
  ('products', 'products', true),
  ('internships', 'internships', true),
  ('competitions', 'competitions', true),
  ('branding', 'branding', true),
  ('internship-applications', 'internship-applications', false),
  ('competition-pitches', 'competition-pitches', false)
ON CONFLICT (id) DO NOTHING;

-- 1. CORE ENUMS
CREATE TYPE IF NOT EXISTS lead_status AS ENUM ('new', 'contacted', 'interested', 'onboarded', 'rejected');
CREATE TYPE IF NOT EXISTS lead_source AS ENUM ('google_maps', 'excel_upload', 'instagram', 'manual');
CREATE TYPE IF NOT EXISTS verification_status AS ENUM ('pending', 'approved', 'rejected', 'resubmission_requested');
CREATE TYPE IF NOT EXISTS flag_status AS ENUM ('open', 'under_review', 'resolved', 'dismissed');
CREATE TYPE IF NOT EXISTS fraud_status AS ENUM ('new', 'acknowledged', 'investigating', 'resolved', 'dismissed');

-- 2. CORE TABLES (Reconstructed from DB state)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id),
    updated_at TIMESTAMPTZ,
    full_name TEXT,
    avatar_url TEXT,
    handle TEXT CHECK (char_length(handle) >= 3),
    role TEXT,
    banner_url TEXT,
    opening_hours TEXT,
    public_key TEXT,
    public_key_digest TEXT
);

CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC CHECK (price >= 0),
    category TEXT,
    image_url TEXT,
    seller_id UUID REFERENCES public.profiles(id),
    location TEXT,
    status TEXT DEFAULT 'active',
    amenities TEXT[] DEFAULT '{}'::text[],
    room_types TEXT[] DEFAULT '{}'::text[],
    occupancy INTEGER
);

-- 3. MODULE TABLES (From Source Files)
-- -----------------------------------------------------------------------------

-- Audit Logs
CREATE TABLE IF NOT EXISTS public.audit_log (
    id BIGSERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    admin_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    details TEXT,
    target_type TEXT,
    target_id TEXT
);

-- Lead Management
CREATE TABLE IF NOT EXISTS public.leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    whatsapp_status BOOLEAN DEFAULT false,
    source lead_source DEFAULT 'manual',
    external_id TEXT,
    category TEXT,
    address TEXT,
    city TEXT,
    status lead_status DEFAULT 'new',
    ai_summary TEXT,
    last_contacted_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'::jsonb
);

-- Marketplace Extensions
CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    image_url TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_variants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    value TEXT NOT NULL,
    price_modifier NUMERIC DEFAULT 0,
    stock_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(product_id, user_id)
);

-- Chat System (E2EE)
CREATE TABLE IF NOT EXISTS public.chat_rooms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now(),
    name TEXT,
    avatar TEXT
);

CREATE TABLE IF NOT EXISTS public.chat_participants (
    room_id UUID REFERENCES public.chat_rooms(id),
    user_id UUID REFERENCES auth.users(id),
    joined_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (room_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID REFERENCES public.chat_rooms(id),
    user_id UUID REFERENCES auth.users(id),
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    is_read BOOLEAN DEFAULT false,
    encryption_v INTEGER DEFAULT 1,
    iv TEXT
);

CREATE TABLE IF NOT EXISTS public.chat_room_keys (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    room_id UUID REFERENCES public.chat_rooms(id),
    user_id UUID REFERENCES auth.users(id),
    encrypted_session_key TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 4. FUNCTIONS & RPCs
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION is_chat_participant(room_id_to_check uuid)
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM chat_participants 
    WHERE room_id = room_id_to_check AND user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- 5. RLS POLICIES
-- -----------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles are visible to everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Products are viewable by everyone" ON public.products FOR SELECT USING (true);
CREATE POLICY "Sellers can manage their products" ON public.products FOR ALL USING (auth.uid() = seller_id);

CREATE POLICY "Admins can manage leads" ON public.leads FOR ALL TO authenticated
USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin'));

-- 6. INDEXES
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category);
CREATE INDEX IF NOT EXISTS idx_products_seller_id ON products(seller_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_leads_phone ON public.leads(phone);
CREATE INDEX IF NOT EXISTS idx_leads_status ON public.leads(status);
CREATE INDEX IF NOT EXISTS idx_audit_log_admin_id ON public.audit_log(admin_id);

-- 7. TRIGGERS
-- -----------------------------------------------------------------------------
DROP TRIGGER IF EXISTS update_leads_updated_at ON public.leads;
CREATE TRIGGER update_leads_updated_at
  BEFORE UPDATE ON public.leads
  FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
