import type { HomePosterConfig } from '@/lib/types';

export const defaultHomePosterConfig: HomePosterConfig = {
  heroSlides: [
    {
      id: 'campus-life',
      title: 'Your Campus, Reimagined.',
      subtitle: 'Experience the ultimate student dashboard. Manage stays, expenses, and notes while unlocking exclusive opportunities.',
      imageUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1600&q=80',
      ctaLabel: 'Launch Workspace',
      ctaHref: '/workspace',
      secondaryCtaLabel: 'Explore Marketplace',
      secondaryCtaHref: '/marketplace',
      tag: 'Student Essentials',
    },
    {
      id: 'market-discoveries',
      title: 'Marketplace for Students',
      subtitle: 'Buy and sell verified campus essentials. From study tables to lab coats, find what you need within your budget.',
      imageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1600&q=80',
      ctaLabel: 'Start Shopping',
      ctaHref: '/marketplace',
      secondaryCtaLabel: 'Find Housing',
      secondaryCtaHref: '/booking',
      tag: 'Trusted Listings',
    },
    {
      id: 'workspace-upskill',
      title: 'Accelerate Your Career',
      subtitle: 'Discover internships, hackathons, and mentorship application tracks designed to boost your portfolio.',
      imageUrl: 'https://images.unsplash.com/photo-1529070538774-1843cb3265df?auto=format&fit=crop&w=1600&q=80',
      ctaLabel: 'Find Opportunities',
      ctaHref: '/workspace',
      secondaryCtaLabel: 'View Competitions',
      secondaryCtaHref: '/workspace/competitions',
      tag: 'Career Growth',
    },
  ],
  quickAccessCards: [
    {
      id: 'quick-study',
      title: 'Study & Notes',
      description: 'Keep your exam prep, shared notes, and class material in one place.',
      href: '/notes',
      imageUrl: 'https://images.unsplash.com/photo-1521986329282-0436c1e63c86?auto=format&fit=crop&w=800&q=80',
      icon: 'users',
    },
    {
      id: 'quick-booking',
      title: 'Library Booking',
      description: 'Reserve library seats and quiet corners before they fill up.',
      href: '/booking',
      imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
      icon: 'sparkles',
    },
    {
      id: 'quick-market',
      title: 'Marketplace',
      description: 'Shop verified listings from hostel beds to stationery.',
      href: '/marketplace',
      imageUrl: 'https://images.unsplash.com/photo-1515169067865-5387ec356754?auto=format&fit=crop&w=800&q=80',
      icon: 'store',
    },
    {
      id: 'quick-workspace',
      title: 'Workspace',
      description: 'Level up with internships and competitions hand-picked for you.',
      href: '/workspace',
      imageUrl: 'https://images.unsplash.com/photo-1523475472560-d2df97ec485c?auto=format&fit=crop&w=800&q=80',
      icon: 'rocket',
    },
  ],
  curatedCollections: [
    {
      id: 'collection-workspace',
      title: 'Career & Skill Tracks',
      description: 'Follow curated paths that mix internships, competitions, and projects.',
      href: '/workspace',
      imageUrl: 'https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=1400&q=80',
    },
    {
      id: 'collection-market',
      title: 'Campus Marketplace',
      description: 'Browse community-approved vendors and student-led services.',
      href: '/marketplace',
      imageUrl: 'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1400&q=80',
    },
    {
      id: 'collection-work',
      title: 'Career Boost Corner',
      description: 'Showcase your skills, join competitions, and get noticed.',
      href: '/workspace',
      imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1400&q=80',
    },
  ],
  mobileDeals: [
    {
      title: 'Last-Minute Library Slots',
      subtitle: 'Grab remaining seats in reading rooms and labs before exams.',
      href: '/booking',
      gradient: 'from-blue-500 via-purple-500 to-pink-500',
      icon: 'sparkles',
    },
    {
      title: 'UniNest Deals',
      subtitle: 'Unlock exclusive offers and cashback on student favorites.',
      href: '/marketplace',
      gradient: 'from-amber-500 via-orange-500 to-rose-500',
      icon: 'gift',
    },
  ],
  stats: [
    {
      value: 12000,
      label: 'Students onboarded',
      icon: 'users',
      isPlus: true,
    },
    {
      value: 480,
      label: 'Vendors listed',
      icon: 'store',
      isPlus: true,
    },
    {
      value: 3200,
      label: 'Daily student actions',
      icon: 'message-square',
      isPlus: true,
    },
  ],
  testimonials: [
    {
      name: 'Ayesha Khan',
      quote: 'UniNest keeps me updated on everything—from hostel events to study groups—without the noise.',
      school: 'SRM Institute of Science and Technology',
      avatar: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=256&q=80',
    },
    {
      name: 'Rohan Sharma',
      quote: 'I discovered my internship and locked in a verified PG through UniNest in less than a week.',
      school: 'IIT Bombay',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    },
    {
      name: 'Nandini Rao',
      quote: 'It feels like my entire campus life lives in one app—marketplace, workspace, and more.',
      school: 'Christ University',
      avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=256&q=80',
    },
  ],
  timeline: [
    {
      year: '2022',
      title: 'UniNest was born',
      description: 'Built to empower students with a digital-first campus experience.',
      icon: 'sparkles',
    },
    {
      year: '2023',
      title: 'Marketplace launched',
      description: 'Local vendors and student entrepreneurs found their new home.',
      icon: 'store',
    },
    {
      year: '2024',
      title: 'Campus tools expansion',
      description: 'Introduced smarter booking, verification, and shared student resources.',
      icon: 'users',
    },
    {
      year: '2025',
      title: 'Workspace 2.0',
      description: 'AI-powered discovery for internships, competitions, and mentors.',
      icon: 'rocket',
    },
  ],
};
